using Chairly.Api.Shared.Mediator;
using Chairly.Api.Shared.Results;
using Chairly.Api.Shared.Tenancy;
using Chairly.Domain.Entities;
using Chairly.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using OneOf;
using OneOf.Types;

#pragma warning disable CA1812
namespace Chairly.Api.Features.Billing.RegenerateInvoice;

internal sealed class RegenerateInvoiceHandler(ChairlyDbContext db, InvoiceLineItemBuilder lineItemBuilder) : IRequestHandler<RegenerateInvoiceCommand, OneOf<InvoiceResponse, NotFound, Unprocessable>>
{
    public async Task<OneOf<InvoiceResponse, NotFound, Unprocessable>> Handle(RegenerateInvoiceCommand command, CancellationToken cancellationToken = default)
    {
        ArgumentNullException.ThrowIfNull(command);

        var invoice = await db.Invoices
            .Include(i => i.LineItems)
            .FirstOrDefaultAsync(i => i.Id == command.Id && i.TenantId == TenantConstants.DefaultTenantId, cancellationToken)
            .ConfigureAwait(false);

        if (invoice is null)
        {
            return new NotFound();
        }

        if (invoice.SentAtUtc != null || invoice.PaidAtUtc != null || invoice.VoidedAtUtc != null)
        {
            return new Unprocessable("Alleen concept-facturen kunnen opnieuw worden gegenereerd");
        }

        var booking = await db.Bookings
            .Include(b => b.BookingServices)
            .FirstOrDefaultAsync(b => b.Id == invoice.BookingId && b.TenantId == TenantConstants.DefaultTenantId, cancellationToken)
            .ConfigureAwait(false);

        if (booking is null)
        {
            return new NotFound();
        }

        if (booking.CompletedAtUtc == null)
        {
            return new Unprocessable("Boeking is niet afgerond");
        }

        await ReplaceLineItemsAsync(invoice, booking, cancellationToken).ConfigureAwait(false);

        var (clientFullName, clientSnapshot, staffMemberName) = await InvoiceMapper
            .LoadInvoiceContextAsync(db, invoice, cancellationToken)
            .ConfigureAwait(false);

        return InvoiceMapper.ToResponse(invoice, clientFullName, clientSnapshot, staffMemberName);
    }

    private async Task ReplaceLineItemsAsync(Invoice invoice, Booking booking, CancellationToken cancellationToken)
    {
        var newLineItems = await lineItemBuilder.BuildFromBookingAsync(booking.BookingServices, cancellationToken).ConfigureAwait(false);

        // Only replace auto-generated (non-manual) line items. Manual items (discounts,
        // surcharges) added by the user are preserved across regeneration.
        var autoGeneratedItems = invoice.LineItems.Where(li => !li.IsManual).ToList();
        var manualItems = invoice.LineItems.Where(li => li.IsManual).ToList();

        // Update existing auto-generated items in-place and add/remove as needed.
        // For new items beyond the existing count, copy properties into a fresh
        // InvoiceLineItem so EF Core OwnsMany tracking correctly associates
        // the entity with the parent Invoice.
        for (var i = 0; i < Math.Max(autoGeneratedItems.Count, newLineItems.Count); i++)
        {
            if (i < autoGeneratedItems.Count && i < newLineItems.Count)
            {
                // Update existing item in-place
                autoGeneratedItems[i].Description = newLineItems[i].Description;
                autoGeneratedItems[i].Quantity = newLineItems[i].Quantity;
                autoGeneratedItems[i].UnitPrice = newLineItems[i].UnitPrice;
                autoGeneratedItems[i].TotalPrice = newLineItems[i].TotalPrice;
                autoGeneratedItems[i].VatPercentage = newLineItems[i].VatPercentage;
                autoGeneratedItems[i].VatAmount = newLineItems[i].VatAmount;
                autoGeneratedItems[i].SortOrder = newLineItems[i].SortOrder;
                autoGeneratedItems[i].IsManual = newLineItems[i].IsManual;
            }
            else if (i >= autoGeneratedItems.Count)
            {
                // Add new item — use Entry().State to ensure EF Core tracks it as Added
                var item = newLineItems[i];
                invoice.LineItems.Add(item);
                db.Entry(item).State = EntityState.Added;
            }
            else
            {
                // Remove excess old auto-generated item
                invoice.LineItems.Remove(autoGeneratedItems[i]);
            }
        }

        // Re-number sort orders: auto-generated items first, then manual items
        var sortOrder = 0;
        foreach (var item in invoice.LineItems.Where(li => !li.IsManual).OrderBy(li => li.SortOrder))
        {
            item.SortOrder = sortOrder++;
        }

        foreach (var item in manualItems.OrderBy(li => li.SortOrder))
        {
            item.SortOrder = sortOrder++;
        }

        InvoiceMapper.RecalculateInvoiceTotals(invoice);
        await db.SaveChangesAsync(cancellationToken).ConfigureAwait(false);
    }
}
#pragma warning restore CA1812
