var builder = DistributedApplication.CreateBuilder(args);

// WithDataVolume() attaches a named Docker volume so PostgreSQL data survives AppHost restarts.
// The volume name is auto-generated by Aspire (pattern: {app}-postgres-data).
// To list volumes: docker volume ls
// To reset local data intentionally: docker volume rm $(docker volume ls -q --filter name=postgres)
var db = builder.AddPostgres("postgres")
    .WithDataVolume()
    .AddDatabase("ChairlyDb");

// Explicit credentials so developers can log into the RabbitMQ management UI (http://localhost:15672).
// Default credentials: chairly / chairly (see appsettings.json > Parameters).
var rabbitmqUser = builder.AddParameter("rabbitmq-user");
var rabbitmqPassword = builder.AddParameter("rabbitmq-password", secret: true);

// WithDataVolume() persists RabbitMQ data (including credentials) across restarts.
// If credentials change and login fails, delete the stale volume:
//   docker volume rm $(docker volume ls -q --filter name=messaging)
var rabbitmq = builder.AddRabbitMQ("messaging", rabbitmqUser, rabbitmqPassword)
    .WithDataVolume()
    .WithManagementPlugin();

// MailDev provides a local SMTP server and a web UI for inspecting captured emails.
// Web UI: http://localhost:1080 — SMTP: localhost:1025
var maildev = builder.AddContainer("maildev", "maildev/maildev", "2.2.1")
    .WithHttpEndpoint(targetPort: 1080, name: "http")
    .WithEndpoint(targetPort: 1025, name: "smtp");

var smtpEndpoint = maildev.GetEndpoint("smtp");

builder.AddProject<Projects.Chairly_Api>("api")
    .WithReference(db)
    .WaitFor(db)
    .WithReference(rabbitmq)
    .WaitFor(rabbitmq)
    .WaitFor(maildev)
    .WithEnvironment("Smtp__Host", smtpEndpoint.Property(EndpointProperty.Host))
    .WithEnvironment("Smtp__Port", smtpEndpoint.Property(EndpointProperty.Port))
    .WithEnvironment("Smtp__FromAddress", "noreply@chairly.local")
    .WithEnvironment("Smtp__FromName", "Chairly")
    .WithUrlForEndpoint("http", ep => new ResourceUrlAnnotation { Url = "/scalar", DisplayText = "Scalar" });

builder.Build().Run();
