var builder = DistributedApplication.CreateBuilder(args);

// WithDataVolume() attaches a named Docker volume so PostgreSQL data survives AppHost restarts.
// The volume name is auto-generated by Aspire (pattern: {app}-postgres-data).
// To list volumes: docker volume ls
// To reset local data intentionally: docker volume rm $(docker volume ls -q --filter name=postgres)
var postgres = builder.AddPostgres("postgres")
    .WithDataVolume();

var db = postgres.AddDatabase("ChairlyDb");
var websiteDb = postgres.AddDatabase("WebsiteDb");

// Explicit credentials so developers can log into the RabbitMQ management UI (http://localhost:15672).
// Default credentials: chairly / chairly (see appsettings.json > Parameters).
var rabbitmqUser = builder.AddParameter("rabbitmq-user");
var rabbitmqPassword = builder.AddParameter("rabbitmq-password", secret: true);

// WithDataVolume() persists RabbitMQ data (including credentials) across restarts.
// If credentials change and login fails, delete the stale volume:
//   docker volume rm $(docker volume ls -q --filter name=messaging)
var rabbitmq = builder.AddRabbitMQ("messaging", rabbitmqUser, rabbitmqPassword)
    .WithDataVolume()
    .WithManagementPlugin();

// MailDev provides a local SMTP server and a web UI for inspecting captured emails.
// Web UI: http://localhost:1080 — SMTP: localhost:1025
var maildev = builder.AddContainer("maildev", "maildev/maildev", "2.2.1")
    .WithHttpEndpoint(targetPort: 1080, name: "http")
    .WithEndpoint(targetPort: 1025, name: "smtp");

var smtpEndpoint = maildev.GetEndpoint("smtp");

// Keycloak identity provider — realm-per-tenant (ADR-008).
// Admin UI: http://localhost:8080/admin (admin / <keycloakAdminPassword>)
// WithDataVolume() persists realm configuration across restarts.
// After first run, manually create the realm and clients — see docs/keycloak-setup.md.
var keycloakAdminPassword = builder.AddParameter("keycloak-admin-password", secret: true);

var keycloak = builder.AddContainer("keycloak", "quay.io/keycloak/keycloak", "26.2")
    .WithHttpEndpoint(targetPort: 8080, name: "http")
    .WithEnvironment("KEYCLOAK_ADMIN", "admin")
    .WithEnvironment("KEYCLOAK_ADMIN_PASSWORD", keycloakAdminPassword)
    .WithArgs("start-dev")
    .WithVolume("keycloak-data", "/opt/keycloak/data")
    .WithBindMount("keycloak-themes/chairly", "/opt/keycloak/themes/chairly")
    .WithUrlForEndpoint("http", ep => new ResourceUrlAnnotation { Url = "/admin", DisplayText = "Keycloak Admin" });

var keycloakEndpoint = keycloak.GetEndpoint("http");

// Default realm for local development — human-readable name used in Keycloak URLs.
var defaultRealm = builder.Configuration["Chairly:DefaultRealm"]
    ?? throw new InvalidOperationException("Chairly:DefaultRealm is not configured. Run: dotnet user-secrets set \"Chairly:DefaultRealm\" \"chairly\"");
var defaultTenantId = builder.Configuration["Chairly:DefaultTenantId"]
    ?? throw new InvalidOperationException("Chairly:DefaultTenantId is not configured. Run: dotnet user-secrets set \"Chairly:DefaultTenantId\" \"00000000-0000-0000-0000-000000000001\"");

// Keycloak Admin API service account credentials.
var keycloakAdminClientSecret = builder.AddParameter("keycloak-admin-client-secret", secret: true);

builder.AddProject<Projects.Chairly_Api>("api")
    .WithReference(db)
    .WithReference(websiteDb)
    .WaitFor(db)
    .WaitFor(websiteDb)
    .WithReference(rabbitmq)
    .WaitFor(rabbitmq)
    .WaitFor(maildev)
    .WaitFor(keycloak)
    .WithEnvironment("Smtp__Host", smtpEndpoint.Property(EndpointProperty.Host))
    .WithEnvironment("Smtp__Port", smtpEndpoint.Property(EndpointProperty.Port))
    .WithEnvironment("Smtp__FromAddress", builder.Configuration["Smtp:FromAddress"]
        ?? throw new InvalidOperationException("Smtp:FromAddress is not configured. Run: dotnet user-secrets set \"Smtp:FromAddress\" \"noreply@chairly.local\""))
    .WithEnvironment("Smtp__FromName", builder.Configuration["Smtp:FromName"]
        ?? throw new InvalidOperationException("Smtp:FromName is not configured. Run: dotnet user-secrets set \"Smtp:FromName\" \"Chairly\""))
    .WithEnvironment("Keycloak__Url", keycloakEndpoint)
    .WithEnvironment("Keycloak__Realm", defaultRealm)
    .WithEnvironment("Keycloak__ClientId", builder.Configuration["Keycloak:ClientId"]
        ?? throw new InvalidOperationException("Keycloak:ClientId is not configured. Run: dotnet user-secrets set \"Keycloak:ClientId\" \"chairly-frontend\""))
    .WithEnvironment("Keycloak__AdminClientId", builder.Configuration["Keycloak:AdminClientId"]
        ?? throw new InvalidOperationException("Keycloak:AdminClientId is not configured. Run: dotnet user-secrets set \"Keycloak:AdminClientId\" \"chairly-admin\""))
    .WithEnvironment("Keycloak__AdminPassword", keycloakAdminPassword)
    .WithEnvironment("Keycloak__TenantId", defaultTenantId)
    .WithEnvironment("Keycloak__AdminClientSecret", keycloakAdminClientSecret)
    .WithEnvironment("Keycloak__AdminPortalRealm", builder.Configuration["Keycloak:AdminPortalRealm"]
        ?? throw new InvalidOperationException("Keycloak:AdminPortalRealm is not configured. Run: dotnet user-secrets set \"Keycloak:AdminPortalRealm\" \"chairly-admin\""))
    .WithEnvironment("Keycloak__AdminPortalClientId", builder.Configuration["Keycloak:AdminPortalClientId"]
        ?? throw new InvalidOperationException("Keycloak:AdminPortalClientId is not configured. Run: dotnet user-secrets set \"Keycloak:AdminPortalClientId\" \"chairly-admin-portal\""))
    // MailDev SMTP endpoint as seen from Docker containers (Keycloak realm SMTP config).
    // Uses the Docker network hostname ("maildev") and internal target port (1025),
    // not the host-mapped endpoint, because Keycloak runs inside Docker.
    .WithEnvironment("Keycloak__SmtpHost", builder.Configuration["Keycloak:SmtpHost"]
        ?? throw new InvalidOperationException("Keycloak:SmtpHost is not configured. Run: dotnet user-secrets set \"Keycloak:SmtpHost\" \"maildev\""))
    .WithEnvironment("Keycloak__SmtpPort", builder.Configuration["Keycloak:SmtpPort"]
        ?? throw new InvalidOperationException("Keycloak:SmtpPort is not configured. Run: dotnet user-secrets set \"Keycloak:SmtpPort\" \"1025\""))
    .WithUrlForEndpoint("http", ep => new ResourceUrlAnnotation { Url = "/scalar", DisplayText = "Scalar" });

builder.Build().Run();
